---

# driver:
#   name: docker
#   binary: /usr/bin/docker
#   socket: unix:///var/run/docker.sock
#   use_sudo: false
#   forward:
#     - 8080:8080
#
# transport:
#   name: sftp

driver:
  name: dokken 
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  volumes:
  # saves the apt archieves outside of the container
  - /var/cache/apt/archives/:/var/cache/apt/archives/


transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: centos-7
  driver:
    image: centos:7
    privileged: true
    pid_one_command: /usr/lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd

suites:
  - name: default
    run_list:
     - recipe[sample_chef]
    attributes: {}
