---

driver:
  name: docker
  binary: /usr/bin/docker
  socket: unix:///var/run/docker.sock
  use_sudo: false
  forward:
    - 8080:8080

platforms:
- name: ubuntu
  driver_config:
    image: ubuntu:16.04
    platform: ubuntu

transport:
  name: sftp

